version: '3'

services:
  web:
    build: ./truckpad
    command: pipenv run /usr/src/truckpad/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./truckpad/:/usr/src/truckpad/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    build: database/.
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

volumes:
  postgres_data: