# Generated by Django 3.0.4 on 2020-03-24 18:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import nucleo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[(nucleo.models.Genero['m'], 'masculino'), (nucleo.models.Genero['f'], 'feminino'), (nucleo.models.Genero['x'], 'outros')], max_length=1, null=True)),
                ('tipo_habilitacao', models.CharField(blank=True, choices=[(nucleo.models.Genero['m'], 'masculino'), (nucleo.models.Genero['f'], 'feminino'), (nucleo.models.Genero['x'], 'outros')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=7, validators=[nucleo.models.validar_placa])),
                ('proprietario', models.BooleanField(blank=True, null=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.Motorista')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.VeiculoTipo')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_carga', models.BooleanField(blank=True, null=True)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('origem', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destino', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.Terminal')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.Veiculo')),
            ],
        ),
    ]
