# Generated by Django 3.0.4 on 2020-03-23 13:32

from django.db import migrations
from django.contrib.gis.geos import Point


def terminal_create(apps, schema_editor):
    Terminal = apps.get_model('nucleo', 'Terminal')

    db_alias = schema_editor.connection.alias
    Terminal.objects.using(db_alias).bulk_create([
        Terminal(
            pk=1,
            nome="Términal Pé Na Estrada",
            localizacao=Point(-23.5162053, -46.6269594)
        )
    ])


def veiculo_tipo_create(apps, schema_editor):
    VeiculoTipo = apps.get_model('nucleo', 'VeiculoTipo')

    db_alias = schema_editor.connection.alias
    VeiculoTipo.objects.using(db_alias).bulk_create([
        VeiculoTipo(
            pk=1,
            descricao="Caminhão 3/4"
        ),
        VeiculoTipo(
            pk=2,
            descricao="Caminhão Toco"
        ),
        VeiculoTipo(
            pk=3,
            descricao="Caminhão Truck"
        ),
        VeiculoTipo(
            pk=4,
            descricao="Carreta Simples"
        ),
        VeiculoTipo(
            pk=5,
            descricao="Carreta Eixo Extendido"
        ),        
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(terminal_create),
        migrations.RunPython(veiculo_tipo_create)
    ]
