# Generated by Django 3.0.4 on 2020-03-25 18:01
from datetime import date, datetime


from django.db import migrations
from django.contrib.gis.geos import Point


def motorista_create(apps, schema_editor):
    Motorista = apps.get_model('nucleo', 'Motorista')

    db_alias = schema_editor.connection.alias
    Motorista.objects.using(db_alias).bulk_create([
        Motorista(
            pk=1,
            nome="João do Caminhão",
            data_nascimento=date(1982, 1, 1),
            genero='m',
            tipo_habilitacao='E'
        ),
        Motorista(
            pk=2,
            nome="Zé da Carreta",
            data_nascimento=date(1982, 1, 1),
            genero='m',
            tipo_habilitacao='E'
        )
    ])


def veiculo_create(apps, schema_editor):
    Veiculo = apps.get_model('nucleo', 'Veiculo')

    Motorista = apps.get_model('nucleo', 'Motorista')

    VeiculoTipo = apps.get_model('nucleo', 'VeiculoTipo')
    veiculo_tipo = VeiculoTipo.objects.get(pk=1)

    motorista_1 = Motorista.objects.get(pk=1)
    motorista_2 = Motorista.objects.get(pk=2)

    db_alias = schema_editor.connection.alias
    Veiculo.objects.using(db_alias).bulk_create([
        Veiculo(
            pk=1,
            motorista=motorista_1,
            placa='XYZ1234',
            proprietario=True,
            tipo=veiculo_tipo
        ),
        Veiculo(
            pk=2,
            motorista=motorista_2,
            placa='XYZ1235',
            proprietario=False,
            tipo=veiculo_tipo
        )
    ])


def terminal_veiculo_create(apps, schema_editor):
    TerminalVeiculo = apps.get_model('nucleo', 'TerminalVeiculo')

    Terminal = apps.get_model('nucleo', 'Terminal')
    terminal = Terminal.objects.get(pk=1)

    Veiculo = apps.get_model('nucleo', 'Veiculo')
    veiculo_1 = Veiculo.objects.get(pk=1)
    veiculo_2 = Veiculo.objects.get(pk=2)


    db_alias = schema_editor.connection.alias
    TerminalVeiculo.objects.using(db_alias).bulk_create([
        TerminalVeiculo(
            pk=1,
            possui_carga=True,
            entrada=datetime(2020, 3, 25, 8, 0, 0),
            saida=datetime(2020, 3, 25, 10, 0, 0),
            origem=Point(-23.5162053, -46.6269594),
            destino=Point(-23.5162053, -47.6269594),
            terminal=terminal,
            veiculo=veiculo_1
        ),
        TerminalVeiculo(
            pk=2,
            possui_carga=True,
            entrada=datetime(2020, 3, 25, 8, 0, 0),
            saida=datetime(2020, 3, 25, 10, 0, 0),
            origem=Point(-23.5162053, -46.6269594),
            destino=Point(-23.5162053, -47.6269594),
            terminal=terminal,
            veiculo=veiculo_2
        )
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002'),
    ]

    operations = [
        migrations.RunPython(motorista_create),
        migrations.RunPython(veiculo_create),
        migrations.RunPython(terminal_veiculo_create),
    ]
